package com.pineypiney.mtt.dnd.stats

import com.pineypiney.mtt.dnd.stats.Ability.*

enum class Skill(val ability: Ability) {
	ACROBATICS(DEXTERITY),
	ANIMAL_HANDLING(WISDOM),
	ARCANA(INTELLIGENCE),
	ATHLETICS(STRENGTH),
	DECEPTION(CHARISMA),
	HISTORY(INTELLIGENCE),
	INSIGHT(WISDOM),
	INTIMIDATION(CHARISMA),
	INVESTIGATION(INTELLIGENCE),
	MEDICINE(WISDOM),
	NATURE(INTELLIGENCE),
	PERCEPTION(WISDOM),
	PERFORMANCE(CHARISMA),
	PERSUASION(CHARISMA),
	RELIGION(INTELLIGENCE),
	SLEIGHT_OF_HAND(DEXTERITY),
	STEALTH(DEXTERITY),
	SURVIVAL(WISDOM)
}